// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: exercicio05/grpc/arquivo.proto

package arquivo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conteudo      string                 `protobuf:"bytes,1,opt,name=conteudo,proto3" json:"conteudo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_exercicio05_grpc_arquivo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_exercicio05_grpc_arquivo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_exercicio05_grpc_arquivo_proto_rawDescGZIP(), []int{0}
}

func (x *Args) GetConteudo() string {
	if x != nil {
		return x.Conteudo
	}
	return ""
}

type LinhasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linhas        int32                  `protobuf:"varint,1,opt,name=linhas,proto3" json:"linhas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinhasResponse) Reset() {
	*x = LinhasResponse{}
	mi := &file_exercicio05_grpc_arquivo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinhasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinhasResponse) ProtoMessage() {}

func (x *LinhasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercicio05_grpc_arquivo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinhasResponse.ProtoReflect.Descriptor instead.
func (*LinhasResponse) Descriptor() ([]byte, []int) {
	return file_exercicio05_grpc_arquivo_proto_rawDescGZIP(), []int{1}
}

func (x *LinhasResponse) GetLinhas() int32 {
	if x != nil {
		return x.Linhas
	}
	return 0
}

var File_exercicio05_grpc_arquivo_proto protoreflect.FileDescriptor

var file_exercicio05_grpc_arquivo_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x30, 0x35, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x61, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x61, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x22, 0x22, 0x0a, 0x04, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x75, 0x64, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x75, 0x64, 0x6f, 0x22, 0x28, 0x0a,
	0x0e, 0x4c, 0x69, 0x6e, 0x68, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x68, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x69, 0x6e, 0x68, 0x61, 0x73, 0x32, 0x42, 0x0a, 0x0e, 0x41, 0x72, 0x71, 0x75, 0x69,
	0x76, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x4c, 0x69, 0x6e,
	0x68, 0x61, 0x73, 0x12, 0x0d, 0x2e, 0x61, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x2e, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x17, 0x2e, 0x61, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x2e, 0x4c, 0x69, 0x6e,
	0x68, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x65,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x30, 0x35, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x61, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_exercicio05_grpc_arquivo_proto_rawDescOnce sync.Once
	file_exercicio05_grpc_arquivo_proto_rawDescData []byte
)

func file_exercicio05_grpc_arquivo_proto_rawDescGZIP() []byte {
	file_exercicio05_grpc_arquivo_proto_rawDescOnce.Do(func() {
		file_exercicio05_grpc_arquivo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercicio05_grpc_arquivo_proto_rawDesc), len(file_exercicio05_grpc_arquivo_proto_rawDesc)))
	})
	return file_exercicio05_grpc_arquivo_proto_rawDescData
}

var file_exercicio05_grpc_arquivo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exercicio05_grpc_arquivo_proto_goTypes = []any{
	(*Args)(nil),           // 0: arquivo.Args
	(*LinhasResponse)(nil), // 1: arquivo.LinhasResponse
}
var file_exercicio05_grpc_arquivo_proto_depIdxs = []int32{
	0, // 0: arquivo.ArquivoService.Linhas:input_type -> arquivo.Args
	1, // 1: arquivo.ArquivoService.Linhas:output_type -> arquivo.LinhasResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exercicio05_grpc_arquivo_proto_init() }
func file_exercicio05_grpc_arquivo_proto_init() {
	if File_exercicio05_grpc_arquivo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercicio05_grpc_arquivo_proto_rawDesc), len(file_exercicio05_grpc_arquivo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercicio05_grpc_arquivo_proto_goTypes,
		DependencyIndexes: file_exercicio05_grpc_arquivo_proto_depIdxs,
		MessageInfos:      file_exercicio05_grpc_arquivo_proto_msgTypes,
	}.Build()
	File_exercicio05_grpc_arquivo_proto = out.File
	file_exercicio05_grpc_arquivo_proto_goTypes = nil
	file_exercicio05_grpc_arquivo_proto_depIdxs = nil
}
